config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [

    # Utils
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

# Translition
prefix_default_language = False
urlpatterns += i18n_patterns(
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("wincly.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # App
    path("", include("app.urls")),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

wincly/app/urls.py
from django.urls import path, include

from app.views import HomeView, HotelView, AboutView, HotelDetailView, ContactView

# NameSpace
app_name = 'App'


urlpatterns = [

    path('', HomeView.as_view(), name="home"),
    path('Hotels', HotelView.as_view(), name="hotels"),
    path('Hotels/<slug>', HotelDetailView.as_view(), name="hotel"),
    path('About', AboutView.as_view(), name="about"),
    path('Contact', ContactView.as_view(), name="contact"),

    # DRF API
    # path('API/', include('app.api.urls')),

]

wincly/users/urls.py
from django.urls import path

from wincly.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

wincly/app/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from taggit.managers import TaggableManager
from django.utils import timezone
from django.urls import reverse
from app.utils.Unique_Slug_Generator import unique_slug_generator
from django.utils.translation import ugettext_lazy as _


User = settings.AUTH_USER_MODEL


# initial a directory for files of each user
def upload_path(self, filename):
    # file will be uploaded to MEDIA_ROOT/year-month-day/UserName/FileName
    # return ('Uploads/{0}/{1}/{2}'.format(strftime('%Y-%m-%d'), self.author, filename))
    return ('{0}/{1}'.format(self.user, filename))



class HotelQuerySet(models.query.QuerySet):
    def search(self, query):
        if query:
            query = query.strip()
            return self.filter(
                Q(name__icontains=query)
                | Q(country__icontains=query)
                | Q(city__icontains=query)
                | Q(content__icontains=query)
                | Q(summary__icontains=query)
                | Q(user__username__icontains=query)
                | Q(slug__icontains=query)
                | Q(tags__name__icontains=query)
            ).distinct()

        return self



# Hotel Model Manager
class HoteManager(models.Manager):
    def get_queryset(self):
        return HotelQuerySet(self.model, using=self._db)

    # Active Hotels
    def active(self, *args, **kwargs):
        return super(HoteManager, self).filter(
            draft=False, publish__lte=timezone.now()
        )

    # Search
    def search(self, query):
        # if query:
        #     # qs = self.get_queryset().filter(
        #     qs = self.active().filter(
        #                                 Q(title__icontains=query) |
        #                                 Q(content__icontains=query) |
        #                                 Q(author__first_name__icontains=query) |
        #                                 Q(author__last_name__icontains=query) |
        #                                 Q(tags__name__icontains=query)
        #                             ).distinct()
        #     return qs
        # return None
        return self.get_queryset().search(query)




class Hotel(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = _('User'))
    name = models.CharField(max_length = 255, verbose_name = _('Name'))
    image = models.ImageField(blank = True, null = True, upload_to = upload_path, verbose_name = _('Image'))
    content = models.TextField(verbose_name = _('Content'))
    summary = models.CharField(max_length = 511, blank = True, null = True, verbose_name = _('Summary'))
    country = models.CharField(max_length = 255, verbose_name = _('Country'))
    city = models.CharField(max_length = 255, verbose_name = _('City'))
    # Date Time Information
    created = models.DateTimeField(auto_now_add = True, auto_now = False, verbose_name = _('Created'))
    updated = models.DateTimeField(auto_now_add = False, auto_now = True, verbose_name = _('Updated'))
    draft = models.BooleanField(default = False, verbose_name = _('Draft'))
    publish = models.DateTimeField(blank = True, null = True, verbose_name = _('Publish'))
    # Utils
    slug = models.SlugField(allow_unicode = True, unique = True, verbose_name = _('Slug'))
    tags = TaggableManager(blank = True, verbose_name = _('Tags'))
    website = models.URLField(blank = True, null = True, verbose_name = _('Website'))
    # booking.com url
    booked = models.URLField(blank = True, null = True, verbose_name = _('Booked at'))


    objects = HoteManager()

    def was_published_recently(self):
        if self.publish:
            now = timezone.now()
            return (self.publish <= now and not self.draft)
        return None

    was_published_recently.admin_order_field = 'publish'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published'


    def get_absolute_url(self):
        return reverse('App:hotel', kwargs={"slug": self.slug})


    class Meta:
        verbose_name = _('Hotel')
        verbose_name_plural = _('Hotels')
        ordering = ['-publish', 'name']

    # formatting hotel objects to show
    def __str__(self):
        return f'{self.name} - {self.created}'


    # OverRiding Save Method
    # https://docs.djangoproject.com/en/2.1/topics/db/models/#overriding-predefined-model-methods
    def save(self, *args, **kwargs):
        self.slug = unique_slug_generator(self)
        # Call the "real" save() method.
        super().save(*args, **kwargs)
        # do_something_else()


# Hotel extra images
class HotelImage(models.Model):
    rel = models.ForeignKey(Hotel, related_name='hotel_image', on_delete = models.CASCADE, verbose_name = _('Hotel'))
    image = models.ImageField(blank = True, null = True, upload_to = upload_path, verbose_name = _('Image'))
    user = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = _('User'))



# Contact Us
class Contact (models.Model):
    first_name = models.CharField(max_length=100, verbose_name=_('First Name'))
    last_name = models.CharField(max_length=100, verbose_name=_('Last Name'))
    email = models.EmailField(unique=False, verbose_name=_('Email'))
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Phone'))
    subject = models.CharField(max_length=100, verbose_name=_('Subject'))
    content = models.TextField(verbose_name=_('Content'))
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name= _('Updated'))
    checked = models.BooleanField(default = False, verbose_name = _('Checked'))

    class Meta:
        verbose_name = _('Contact Us')
        verbose_name_plural = _('Contact Us')

    def __str__(self):
        return self.subject

wincly/app/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

wincly/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static i18n compress%}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Wincly{% endblock title %}</title>
  <link rel="icon" href="{% static 'img/favicons/Logo-black.png' %}">

  {% block css %}

    <!-- Font Awesome -->
    {% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-free-5.5.0-web/css/all.css' %}" />

    {% compress css %}

      <!-- Bootstrap core CSS -->
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Material Design Bootstrap -->
      <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
      <!-- Your custom styles (optional) -->
      <!-- <link href="css/style.min.css" rel="stylesheet"> -->
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
      <style type="text/css">

        html,
        body,
        header,
        .carousel {
          height: 100%;
        }

        @media (min-width: 800px) and (max-width: 850px) {
                .navbar:not(.top-nav-collapse) {
                    background: #1C2331!important;
                }
            }
      </style>

    {% endcompress %}
  {% endblock %}

</head>

<body>

  {% get_current_language as LANGUAGE_CODE %}
  <!-- Fa -->
  {% if LANGUAGE_CODE == "fa" %}
    <style type="text/css">
      html,
      body {
        direction: rtl;
        text-align: right;
        font-family: 'IranSans';
      }
    </style>
  <!-- Other -->
  {% else %}
      <style type="text/css">
        html,
        body {
          direction: ltr;
          text-align: left;
          font-family: 'IranSans';
        }
      </style>
  {% endif %}

  <!--Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar" id="navBar">
    {% comment %} <a class="navbar-brand" href="{% url 'App:home' %}">Navbar</a> {% endcomment %}
    <!-- Brand -->
    <a class="navbar-brand fontBold" href="{% url 'App:home' %}" id="navBrand">
      <div class="row">
        <img src="{% static 'img/logo-white.png' %}" width="50" height="50" />
      </div>
    </a>
    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">

      <!-- Brand -->
      <a class="navbar-brand fontBold" href="{% url 'App:home' %}" id="navBrand">
        <div class="row">
          <!-- <div>
            <img src="{% static 'img/logo-white.png' %}" width="50" />
          </div> -->
          <div>
            <strong id="bm">The Wincly Hotels Magazine</strong>
            <br />
            <span id="smTxt">By W-Incorporation</span>
          </div>
        </div>
      </a>

      <!-- Left links -->
      <ul class="navbar-nav mr-auto">
        <!-- Home -->
        <li class="nav-item" id="Home">
          <a class="nav-link" href="{% url 'App:home' %}">{% trans 'Home' %}
          </a>
        </li>
        <!-- Hotels -->
        <li class="nav-item" id="Hotels">
          <a class="nav-link" href="{% url 'App:hotels' %}">{% trans 'Hotels' %}</a>
        </li>
        <!-- About -->
        <li class="nav-item" id="About">
          <a class="nav-link" href="{% url 'App:about' %}">{% trans 'About' %}</a>
        </li>
        <!-- Contact Us -->
        <li class="nav-item" id="ContactUs">
          <a class="nav-link" href="{% url 'App:contact' %}">{% trans 'Contact us' %}</a>
        </li>

        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">Dropdown
          </a>
          <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>  -->

      </ul>
      <!-- Right links -->
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <!-- Social -->
        <!-- <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-twitter"></i>
          </a>
        </li> -->
        <!-- Profile -->
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
      </ul>
    </div>
  </nav>
  <!--/.Navbar -->


  <!-- Back to top -->
  <a class="btn-floating blue-gradient" id="back2Top" title="Back to top" href="#">
    <img src="{% static '/img/ExpandLess.png' %}" width="50"/>
  </a>

  {% block main_content %}


  {% endblock main_content %}

  <!--  Messages -->
  <div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    {% endif %}
  </div>

  <!-- Content -->
  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>
  {% block modal %}{% endblock modal %}

  <!--Footer-->
  <footer class="page-footer text-center font-small">

    <!-- Social icons -->
    <div class="p-4">

      <a href="https://telegram.me/W_Inc" target="_blank">
        <i class="fab fa-telegram-plane fa-lg mr-3" style="color: #0084ff;"></i>
      </a>

      <a href="https://www.instagram.com/winclymag" target="_blank">
        <i class="fab fa-instagram fa-lg mr-3" style="color: #e4405f;"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="row footer-copyright py-3">
      <div class="col">
        <p class="alignMid">
          Developed By <strong>SMBH</strong>
        </p>
      </div>
      <div class="col">
        <p class="alignMid" style="direction: ltr;">
          ©
          2018
          {% blocktrans %}
          Wincly Magazine
          All Rights Reserved.
          {% endblocktrans %}
        </p>
      </div>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
  <!-- childs -->
  {% block javascript %}
    {% compress js %}
    {% endcompress %}
  {% endblock javascript %}

</body>

</html>

wincly/app/templates/base_original.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Wincly{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Wincly</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 

wincly/app/templates/contact_us.html
{% extends "base.html" %}
{% block title %}
  {{ block.super }} | Contact Us
{% endblock title %}
{% load static i18n %}
{% block css %}
  {{ block.super }}
  <!-- Customize -->
  <link rel="stylesheet" href="{% static 'css/contact_us.css' %}" />
{% endblock css %}

{% block javascript %}
  {{ block.super }}
  <!-- Customize -->
  <script src="{% static 'js/contact_us.js' %}"></script>

  {% endblock javascript %}

{% block content %}


<div id="contact_main_div">


  <!-- Contact -->
  <section class="my-5" id="contact">


    <!-- Form row -->
    <div class="row col-lg-12 col-md-12 col-sm-12">

      <!-- Form container -->
      <div class="col-lg-6 col-md-12 col-sm-12 mb-4">

        <!-- Form  -->
        <form class="card" id="contact-form" method="POST">{% csrf_token %}
          <div class="card-body">
            <!-- Header -->
            <div class="form-header accent-1">
              <h3 class="mt-2">
                <i class="fas fa-envelope md-24 mt-4 blue-text"></i>
                Write to Me:</h3>
            </div>
            <p class="dark-grey-text">We'll write rarely, but only the best content.</p>

            <!-- Messages -->
            {% if messages %}
            <ul class="messages alert alert-info">
              {% for message in messages %}
              <li id="message_{{ forloop.counter }}" {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
              </li>
              {% endfor %}
            </ul>
            {% endif %}

            <!-- Errors -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              {% for err in form.errors %} {{ err }} {% endfor %}
            </div>
            {% endif %}
            <!-- Name -->
            {% comment %} {{ form.first_name.errors }} {% endcomment %}
            <div class="md-form">
              <input type="text" id="id_first_name" class="form-control" name="first_name" maxlength='100' autocomplete="off" required />
              <label for="{{ form.first_name.label }}">
                <span>
                  <i class="fa fa-user grey-text"></i>
                </span> Name *
              </label>
            </div>
            <!-- Email -->
            {% comment %} {{ form.email.errors }} {% endcomment %}
            <div class="md-form">
              <input type="email" id="id_email" class="form-control" name="email" maxlength='254' autocomplete="off" required />
              <label for="{{ form.email.label }}">
                <span>
                  <i class="fa fa-envelope grey-text"></i>
                </span>{{ form.email.label }} *
              </label>
            </div>
            <!-- Phone -->
            {% comment %} {{ form.phone.errors }} {% endcomment %}
            <div class="md-form">
              <input type="text" id="id_phone" class="form-control" name="phone" maxlength='20' autocomplete="off" />
              <label for="{{ form.phone.label }}">
                <span>
                  <i class="fa fa-mobile grey-text"></i>
                </span>{{ form.phone.label }}
              </label>
            </div>
            <!-- Subject -->
            {% comment %} {{ form.subject.errors }} {% endcomment %}
            <div class="md-form">
              <input type="text" id="id_ubject" class="form-control" name="subject" maxlength='100' autocomplete="off" required />
              <label for="{{ form.subject.label }}">
                <span>
                  <i class="fa fa-tag grey-text"></i>
                </span>{{ form.subject.label }} *
              </label>
            </div>
            <!-- Content -->
            {% comment %} {{ form.content.errors }} {% endcomment %}
            <div class="md-form">
              <textarea type="text" id="id_content" class="form-control md-textarea" cols="30" rows="6" name="content" required></textarea>
              <label for="{{ form.content.label }}">
                <span>
                  <i class="fa fa-comment" aria-hidden="true"></i>
                </span> {{ form.content.label }} *
              </label>
            </div>

            <div class="text-center">
              <button class="btn btn-blue" type="submit">Send</button>
            </div>
          </div>
        </form>

      </div>


      <!-- Map container -->
      <div class="col-lg-6 col-md-12 col-sm-12">

        <!-- Google map-->
        <div id="Map" class="rounded z-depth-1-half map-container">

          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d23054.49828412707!2d50.94513869495479!3d35.83122644286641!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1532181565597"
            width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>

        </div>
        <br>
        <!-- Buttons-->
        <div class="row text-center" id="Map-btn">
          <div class="col col-md-4 col-sm-4">
            <a class="btn-floating accent-1 map_icons">
              <i class="fas fa-map-marker-alt mt-4 blue-text"></i>
            </a>
            <p class="mb-md-0">IR Iran, Tehran</p>
          </div>
          <div class="col col-md-4 col-sm-4">
            <a class="btn-floating accent-1 map_icons">
              <i class="fas fa-phone mt-4 blue-text"></i>
            </a>
            <p></p>
            <p class="mb-md-0">9:00 - 21:00</p>
          </div>
          <div class="col col-md-4 col-sm-4">
            <a class="btn-floating accent-1 map_icons">
              <i class="fas fa-envelope mt-4 blue-text"></i>
            </a>
            <p class="mb-0">info@wincly.com</p>
          </div>
        </div>

      </div>


    </div>
    <!-- Grid row -->

  </section>


</div>

<!-- Footer -->
{% block footer %}
<div class="page-footer font-small unique-color-dark pt-0" id="footer">
  <div class="footer-copyright py-3 text-center" style="color : #969696;">
    <span>© <span class="footer_logo">SMB </span>
      <span style="color:royalblue;">H</span>
      All rights reserved.
    </span>
  </div>
</div>
{% endblock footer %} {% endblock content %}